### ISSUE TITLE
a little confusion for input args setting in CIFAR100.sh

### ISSUE THREAD

**Issue by hacql2004** [brjathu/RPSnet#2]
Hi brjathu, when I read script code in ./CIFAR100.sh,  I noticed that there are two input args when calling cifar.py. It seems that they represent gpu-id and task-id respectively.  But since you have used "CUDA_VISIBLE_DEVICES=0" there, it doesn't make any sense to input the gpu-id arg again. Could you please to explain that? Thanks. @brjathu

**Comment by brjathu** [comment]
Hi @hacql2004 , the two input args represent task-id and session-id. The task-id (first one) is not GPU-id. In each session, we may have multiple random paths with each having a task-id. It is confusing in this script, but task-id is not limited to 0-7. Hope you find this useful, if you have any further questions, feel free to contact.

**Comment by hacql2004** [comment]
So, here the second arg(the session-id), represents the id of training mission term? For example, in the first mission term includes samples of the 1st category from cifar10, the second mission term includes samples of the 1-2 categories from cifar10, etc. Do I have a exact understanding? Thanks. @brjathu

**Comment by brjathu** [comment]
Almost correct, Session-1 trains the data from task-1, however, session-2 trains data from task-2 and limited samples saved in the memory of task-1.

**Comment by brjathu** [comment]
For example, session one includes 0-10 classes from CIFAR100 (5000 samples), while session two contains 0-20 samples. However, in session two there will be 5000 samples from 10-20 classes and 2000 samples from memory with 0-10 classes. This memory is kept fixed. Thus, there will be only 1000 samples of classes 0-10 available for session 3.

**Comment by hacql2004** [comment]
Great! Thanks for your clear explain.

**Comment by brjathu** [comment]
You are welcome.
