### ISSUE TITLE
Training with single gpu

### ISSUE THREAD

**Issue by xialeiliu** [brjathu/RPSnet#5]
Does it make sense to train it sequentially using ./cifar100.sh
For instance to learn the 1st task always using one gpu sequentially as followings:
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 0 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 1 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 2 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 3 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 4 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 5 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 6 0 
CUDA_VISIBLE_DEVICES=0 python3 cifar.py 7 0

I got some outputs at about 7th task, which  looks weird. why train path is almost all zeros? Is the path selected correctly?

path
 [[1. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 1.]
 [1. 0. 1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 1. 1.]]
fixed_path
 [[1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
train_path
 [[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

**Comment by xialeiliu** [comment]
I checked the confusion matrix after training all tasks, the best accuracy is about 44%, I assume this result is not correct?

**Comment by brjathu** [comment]
Hi, Apologies for the late reply. Yes, simply removing & form CIFAR100.sh should make everything sequential, and that perfectly fine. This way you can run it on a single GPU. 
for the second question, the network usually gets saturated at the end of the learning as most of the modules are trained (see the fixed path is almost '1's).

Final accuracy should be somewhere close to ~56-58.

**Comment by xialeiliu** [comment]
Thanks! I finally figured it out.  The default parameters from cifar. py are different from the ones reported in the paper, that's why at the beginning I couldn't get the correct results.  I would suggest you change them to the right default parameters, then it's easier for others to replicate the results.

**Comment by brjathu** [comment]
Great! do mind sending a pull request?

**Comment by xialeiliu** [comment]
Yeah, sure. Have a look and see if it is correct.

**Comment by brjathu** [comment]
Great! Thank you very much :)

**Comment by xialeiliu** [comment]
No problem!
